runtime: python38
entrypoint: gunicorn -b:$PORT  -w 2 --max-requests=500 rest-server:application
env_variables:
  CLOUD_SQL_USERNAME : "root"
  CLOUD_SQL_PASSWORD : "root"
  CLOUD_SQL_DATABASE_NAME : "userdata"
  CLOUD_SQL_CONNECTION_NAME : "cloudproject-345422:europe-west2-c:numberplate"
  GAE_ENV : "standard"

instance_class: F4
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 5
  max_instances: 100
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50